export const ACTION_LABELS: Record<string, { label: string; color: string }> = {
  created:          { label: 'เพิ่ม Asset เข้าระบบ',     color: 'bg-green-500' },
  updated:          { label: 'แก้ไขข้อมูล',               color: 'bg-blue-500' },
  assigned:         { label: 'มอบหมายให้',                color: 'bg-indigo-500' },
  transferred:      { label: 'โอนย้าย',                   color: 'bg-purple-500' },
  image_added:      { label: 'อัปโหลดรูปถ่าย',            color: 'bg-teal-500' },
  image_removed:    { label: 'ลบรูปภาพ',                  color: 'bg-red-400' },
  imported:         { label: 'นำเข้าจาก Import',          color: 'bg-gray-400' },
  deleted:          { label: 'ลบ Asset',                  color: 'bg-red-600' },
  unassigned:       { label: 'เอาผู้ใช้งานออก',           color: 'bg-orange-400' },
  received:         { label: 'รับเครื่อง',                color: 'bg-cyan-500' },
  repair_requested: { label: 'แจ้งซ่อม',                  color: 'bg-amber-500' },
  repair_resolved:  { label: 'ซ่อมเสร็จ',                 color: 'bg-green-600' },
  spare_assigned:   { label: 'จ่าย Spare ระหว่างซ่อม',    color: 'bg-blue-400' },
  spare_returned:   { label: 'คืน Spare',                  color: 'bg-teal-400' },
  condition_check:  { label: 'ตรวจสภาพเครื่อง',            color: 'bg-violet-500' },
  license_added:    { label: 'เพิ่มโปรแกรม',               color: 'bg-emerald-500' },
  license_updated:  { label: 'แก้ไขโปรแกรม',              color: 'bg-blue-400' },
  license_removed:  { label: 'ลบโปรแกรม',                 color: 'bg-red-400' },
  damaged:          { label: 'ชำรุด — รอตัดจำหน่าย',      color: 'bg-orange-500' },
  writeoff:         { label: 'ตัดจำหน่าย',                color: 'bg-red-700' },
}
